#!/usr/bin/env node
// Generates src/mask.js — the packed land bitmask every dot grid derives from.
//
// Source: Natural Earth 110m land polygons (public domain,
// https://www.naturalearthdata.com/about/terms-of-use/), fetched as GeoJSON
// from the official natural-earth-vector mirror. Rasterized here at MASK_W ×
// MASK_H (equirectangular: x = lon, y = lat, linear) with per-row scanline
// polygon filling — edge crossings per latitude row, sorted, filled between
// pairs (even-odd rule). That's O(edges × rows), fast enough to run in a
// second; naive point-in-polygon per cell would be ~1000× slower.
//
// Output: one base64 string (MASK_W*MASK_H bits, row-major from lat +90 down,
// lon -180 → +180). ~22 KB — the whole world, any resolution, derived.
//
// Run: node scripts/generate-mask.js   (network access required; commit the
// regenerated src/mask.js — consumers never run this.)

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const MASK_W = 512;
const MASK_H = 256;
const SOURCE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson";

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`fetch failed: ${res.status}`);
const geojson = await res.json();

// Collect every polygon ring (outer + holes — even-odd handles both the same
// way: a point inside a hole crosses one extra edge and flips back to sea).
const rings = [];
for (const feature of geojson.features) {
  const g = feature.geometry;
  const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
  for (const poly of polys) for (const ring of poly) rings.push(ring);
}

const bits = new Uint8Array((MASK_W * MASK_H) / 8);

for (let row = 0; row < MASK_H; row++) {
  // Sample at the CELL CENTER latitude, top row = +90 edge.
  const lat = 90 - ((row + 0.5) * 180) / MASK_H;
  const crossings = [];

  for (const ring of rings) {
    for (let i = 0; i < ring.length - 1; i++) {
      const [x1, y1] = ring[i];
      const [x2, y2] = ring[i + 1];
      // Edge crosses this latitude? (half-open interval avoids double-counting
      // vertices that sit exactly on the scanline)
      if (y1 <= lat === y2 <= lat) continue;
      crossings.push(x1 + ((lat - y1) / (y2 - y1)) * (x2 - x1));
    }
  }

  crossings.sort((a, b) => a - b);
  // Fill between pairs of crossings (inside land between 0↔1, 2↔3, …).
  for (let k = 0; k + 1 < crossings.length; k += 2) {
    const colStart = Math.ceil(((crossings[k] + 180) / 360) * MASK_W - 0.5);
    const colEnd = Math.floor(((crossings[k + 1] + 180) / 360) * MASK_W - 0.5);
    for (let col = Math.max(0, colStart); col <= Math.min(MASK_W - 1, colEnd); col++) {
      const idx = row * MASK_W + col;
      bits[idx >> 3] |= 1 << (idx & 7);
    }
  }
}

const landCells = bits.reduce((sum, byte) => {
  let b = byte, n = 0;
  while (b) { n += b & 1; b >>= 1; }
  return sum + n;
}, 0);
const landFraction = landCells / (MASK_W * MASK_H);
console.log(`land cells: ${landCells} / ${MASK_W * MASK_H} (${(landFraction * 100).toFixed(1)}% of the equirectangular frame)`);
if (landFraction < 0.2 || landFraction > 0.45) {
  throw new Error("land fraction looks wrong — rasterization bug or bad source data");
}

const base64 = Buffer.from(bits).toString("base64");
const out = `// GENERATED by scripts/generate-mask.js — do not edit by hand.
// Land bitmask, ${MASK_W}×${MASK_H} equirectangular cells (row-major from
// lat +90 down, lon −180 → +180), 1 bit per cell, base64-packed.
// Data: Natural Earth 110m land (public domain, naturalearthdata.com).

export const MASK_W = ${MASK_W};
export const MASK_H = ${MASK_H};

const BITS = /* base64 */ Uint8Array.from(atob("${base64}"), (c) => c.charCodeAt(0));

// Is there land at this latitude/longitude? The single primitive the whole
// renderer derives from.
export function isLand(lat, lon) {
  if (lat > 90 || lat < -90) return false;
  const col = Math.min(MASK_W - 1, Math.max(0, Math.floor(((lon + 180) / 360) * MASK_W)));
  const row = Math.min(MASK_H - 1, Math.max(0, Math.floor(((90 - lat) / 180) * MASK_H)));
  const idx = row * MASK_W + col;
  return (BITS[idx >> 3] & (1 << (idx & 7))) !== 0;
}
`;

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(join(here, "..", "src", "mask.js"), out);
console.log("wrote src/mask.js");
